// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test_example.proto

//包名，通过protoc生成时go文件时

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//手机类型
//枚举类型第一个字段必须为0
type PhoneType int32

const (
	PhoneType_HOME PhoneType = 0
	PhoneType_WORK PhoneType = 1
)

var PhoneType_name = map[int32]string{
	0: "HOME",
	1: "WORK",
}

var PhoneType_value = map[string]int32{
	"HOME": 0,
	"WORK": 1,
}

func (x PhoneType) String() string {
	return proto.EnumName(PhoneType_name, int32(x))
}

func (PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c3b7610a3c283ea, []int{0}
}

//手机
type Phone struct {
	Type                 PhoneType `protobuf:"varint,1,opt,name=type,proto3,enum=example.PhoneType" json:"type,omitempty"`
	Number               string    `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Phone) Reset()         { *m = Phone{} }
func (m *Phone) String() string { return proto.CompactTextString(m) }
func (*Phone) ProtoMessage()    {}
func (*Phone) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c3b7610a3c283ea, []int{0}
}

func (m *Phone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Phone.Unmarshal(m, b)
}
func (m *Phone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Phone.Marshal(b, m, deterministic)
}
func (m *Phone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Phone.Merge(m, src)
}
func (m *Phone) XXX_Size() int {
	return xxx_messageInfo_Phone.Size(m)
}
func (m *Phone) XXX_DiscardUnknown() {
	xxx_messageInfo_Phone.DiscardUnknown(m)
}

var xxx_messageInfo_Phone proto.InternalMessageInfo

func (m *Phone) GetType() PhoneType {
	if m != nil {
		return m.Type
	}
	return PhoneType_HOME
}

func (m *Phone) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

//人
type Personal struct {
	//后面的数字表示标识号
	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	//repeated表示可重复
	//可以有多个手机
	Phones               []*Phone `protobuf:"bytes,3,rep,name=phones,proto3" json:"phones,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Personal) Reset()         { *m = Personal{} }
func (m *Personal) String() string { return proto.CompactTextString(m) }
func (*Personal) ProtoMessage()    {}
func (*Personal) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c3b7610a3c283ea, []int{1}
}

func (m *Personal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Personal.Unmarshal(m, b)
}
func (m *Personal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Personal.Marshal(b, m, deterministic)
}
func (m *Personal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Personal.Merge(m, src)
}
func (m *Personal) XXX_Size() int {
	return xxx_messageInfo_Personal.Size(m)
}
func (m *Personal) XXX_DiscardUnknown() {
	xxx_messageInfo_Personal.DiscardUnknown(m)
}

var xxx_messageInfo_Personal proto.InternalMessageInfo

func (m *Personal) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Personal) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Personal) GetPhones() []*Phone {
	if m != nil {
		return m.Phones
	}
	return nil
}

//联系簿
type ContactBook struct {
	Persons              []*Personal `protobuf:"bytes,1,rep,name=persons,proto3" json:"persons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ContactBook) Reset()         { *m = ContactBook{} }
func (m *ContactBook) String() string { return proto.CompactTextString(m) }
func (*ContactBook) ProtoMessage()    {}
func (*ContactBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c3b7610a3c283ea, []int{2}
}

func (m *ContactBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactBook.Unmarshal(m, b)
}
func (m *ContactBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactBook.Marshal(b, m, deterministic)
}
func (m *ContactBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactBook.Merge(m, src)
}
func (m *ContactBook) XXX_Size() int {
	return xxx_messageInfo_ContactBook.Size(m)
}
func (m *ContactBook) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactBook.DiscardUnknown(m)
}

var xxx_messageInfo_ContactBook proto.InternalMessageInfo

func (m *ContactBook) GetPersons() []*Personal {
	if m != nil {
		return m.Persons
	}
	return nil
}

func init() {
	proto.RegisterEnum("example.PhoneType", PhoneType_name, PhoneType_value)
	proto.RegisterType((*Phone)(nil), "example.Phone")
	proto.RegisterType((*Personal)(nil), "example.Personal")
	proto.RegisterType((*ContactBook)(nil), "example.ContactBook")
}

func init() { proto.RegisterFile("test_example.proto", fileDescriptor_1c3b7610a3c283ea) }

var fileDescriptor_1c3b7610a3c283ea = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x50, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0x36, 0x5d, 0xd7, 0x6d, 0x6f, 0x50, 0xe6, 0x3b, 0x48, 0x6e, 0x96, 0x1e, 0x46, 0x51, 0xd8,
	0x61, 0xde, 0x3c, 0x2a, 0xa2, 0x20, 0xd2, 0x12, 0x44, 0x8f, 0x92, 0xda, 0x07, 0x16, 0xdb, 0x24,
	0x34, 0x11, 0xec, 0x7f, 0x2f, 0x0d, 0xa9, 0xe2, 0xed, 0xfb, 0xf8, 0x7e, 0x3d, 0x1e, 0xa0, 0x23,
	0xeb, 0xde, 0xe8, 0x5b, 0xf6, 0xa6, 0xa3, 0x83, 0x19, 0xb4, 0xd3, 0xb8, 0x0a, 0x34, 0xbf, 0x87,
	0x65, 0xf5, 0xa1, 0x15, 0xe1, 0x1e, 0x62, 0x37, 0x1a, 0xe2, 0x2c, 0x63, 0x45, 0x7a, 0xc4, 0xc3,
	0xec, 0xf7, 0xea, 0xf3, 0x68, 0x48, 0x78, 0x1d, 0xcf, 0x20, 0x51, 0x5f, 0x7d, 0x4d, 0x03, 0x8f,
	0x32, 0x56, 0x6c, 0x44, 0x60, 0xf9, 0x0b, 0xac, 0x2b, 0x1a, 0xac, 0x56, 0xb2, 0xc3, 0x14, 0xa2,
	0xb6, 0xf1, 0x4d, 0x4b, 0x11, 0xb5, 0x0d, 0x22, 0xc4, 0x4a, 0xf6, 0x14, 0x12, 0x1e, 0xe3, 0x1e,
	0x12, 0x33, 0x55, 0x5b, 0xbe, 0xc8, 0x16, 0xc5, 0xf6, 0x98, 0xfe, 0x5f, 0x14, 0x41, 0xcd, 0xaf,
	0x61, 0x7b, 0xab, 0x95, 0x93, 0xef, 0xee, 0x46, 0xeb, 0x4f, 0xbc, 0x84, 0x95, 0xf1, 0x33, 0x96,
	0x33, 0x9f, 0x3b, 0xfd, 0xcb, 0x85, 0x79, 0x31, 0x3b, 0x2e, 0xce, 0x61, 0xf3, 0x7b, 0x3e, 0xae,
	0x21, 0x7e, 0x28, 0x9f, 0xee, 0x76, 0x27, 0x13, 0x7a, 0x2d, 0xc5, 0xe3, 0x8e, 0xd5, 0x89, 0xff,
	0xc6, 0xd5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x43, 0x99, 0xad, 0xcc, 0x23, 0x01, 0x00, 0x00,
}
