language: 
        - go
go:
- 1.10.x

cache:
  directories:
    - $GOPATH/pkg/mod
env:
        global:
          - GO111MODULE=on
          - GOPROXY=https://proxy.golang.org
          - GOARCH=amd64
          - GOMOD=./go.mod

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
        -  - bash <(curl -s https://codecov.io/bash) -t uuid-repo-token
