language: 
        - go
go:
- 1.10.x

cache:
  directories:
    - $GOPATH/pkg/mod
env:
        global:
          - GO111MODULE=on
          - GOPROXY=https://proxy.golang.org
          - GOARCH=amd64
before_install:
  - if [[ "${GO111MODULE}" = "on" ]]; then mkdir "${HOME}/go"; export GOPATH="${HOME}/go"; fi

install:
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; else make install; fi
  - if [[ "${GO111MODULE}" = "on" ]]; then export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"; fi
  - if [[ "${GO111MODULE}" = "on" ]]; then make tools; fi

