language: 
        - go
go:
- 1.10.x

cache:
  directories:
    - $GOPATH/pkg/mod
env:
        global:
          - GO111MODULE=on
          - GOPROXY=https://proxy.golang.org
          - GOARCH=amd64
       


