language: 
        - go
go:
- 1.10.x

cache:
  directories:
    - $GOPATH/pkg/mod
env:
        global:
          - GO111MODULE=on
          - GOPROXY=https://proxy.golang.org
          - GOARCH=amd64
before_install:
  mkdir "${HOME}/go" && export GOPATH="${HOME}/go" && set GO111MODULE=on

install:
  go mod download && make install &&
  export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}" &&
  make tools

